export enum ProcessDocumentType {
  HomologacaoDeCalculo = 'HomologacaoDeCalculo',
  PeticaoInicial = 'PeticaoInicial',
  AdmissibilidadeRR = 'AdmissibilidadeRR',
  HomologacaoDeAcordo = 'HomologacaoDeAcordo',
  RRReclamada = 'RRReclamada',
  RecursoDeRevista = 'RecursoDeRevista',
  SentencaMerito = 'SentencaMerito',
  SentencaED = 'SentencaED',
  SentencaEE = 'SentencaEE',
  Acordao = 'Acordao',
  AcordaoMerito = 'AcordaoMerito',
  AcordaoED = 'AcordaoED',
  AcordaoAP = 'AcordaoAP',
  AcordaoTRT = 'AcordaoTRT',
  RRAP = 'RRAP',
  EmendaAInicial = 'EmendaAInicial',
  Alvara = 'Alvara',
  PlanilhaCalculo = 'PlanilhaCalculo',
  Parcelamento916 = 'Parcelamento916',
  Impugnacao = 'Impugnacao',
  Garantia = 'Garantia',
  Decisao = 'DecisaoPrevencao',
}
